### PR TITLE
Add auto-publishing to CI

### PR DESCRIPTION
**Pull request by someCatInTheWorld**
i did this a pull request so @nmsderp can approve or disapprove this

### CODE REVIEW

**Comment by nmsderp** [comment]
Can this be on the new offline repo and have it clone the GUI, build it, then make it an electron app

**Comment by nmsderp** [comment]
@thepython555 has made some progress

**Comment by someCatInTheWorld** [comment]
> Can this be on the new offline repo and have it clone the GUI, build it, then make it an electron app

This could be another way to download Snail IDE if the user doesn't want to download their browser all over again and just wants Snail IDE.

**Comment by nmsderp** [comment]
> > Can this be on the new offline repo and have it clone the GUI, build it, then make it an electron app
> 
> This could be another way to download Snail IDE if the user doesn't want to download their browser all over again and just wants Snail IDE.

we decided not to use electron, instead we are using nw.js, which uses a similar method, most people would prefer a desktop app though, both scratch and turbowarp uses the electron method, and penguinmod has hinted on doing it

**Comment by nmsderp** [comment]
> > > Can this be on the new offline repo and have it clone the GUI, build it, then make it an electron app
> > 
> > 
> > This could be another way to download Snail IDE if the user doesn't want to download their browser all over again and just wants Snail IDE.
> 
> we decided not to use electron, instead we are using nw.js, which uses a similar method, most people would prefer a desktop app though, both scratch and turbowarp uses the electron method, and penguinmod has hinted on doing it

but we *may* be able to use tauri if someone figures it out

**Comment by someCatInTheWorld** [comment]
> > > Can this be on the new offline repo and have it clone the GUI, build it, then make it an electron app
> > 
> > 
> > This could be another way to download Snail IDE if the user doesn't want to download their browser all over again and just wants Snail IDE.
> 
> we decided not to use electron, instead we are using nw.js, which uses a similar method, most people would prefer a desktop app though, both scratch and turbowarp uses the electron method, and penguinmod has hinted on doing it

What if they're using a non-privileged account?

**Comment by nmsderp** [comment]
> non-privileged account

most of the time if your account is non-privileged .html files are blocked, for example on ChromeOS if your Chromebook is set to be for a child or school .html is blocked, I think windows does it too and maybe mac. (probably like 70% of the snail ide community uses Chromebook, and are most likely for school)

**Comment by dumorando** [comment]
> > non-privileged account
> 
> most of the time if your account is non-privileged .html files are blocked, for example on ChromeOS if your Chromebook is set to be for a child or school .html is blocked, I think windows does it too and maybe mac. (probably like 70% of the snail ide community uses Chromebook, and are most likely for school)

my school laptop doesnt block html files

**Comment by nmsderp** [comment]
> > > non-privileged account
> > 
> > 
> > most of the time if your account is non-privileged .html files are blocked, for example on ChromeOS if your Chromebook is set to be for a child or school .html is blocked, I think windows does it too and maybe mac. (probably like 70% of the snail ide community uses Chromebook, and are most likely for school)
> 
> my school laptop doesnt block html files

either i am wrong, or they made your accounts a little less restrictive somehow.

**Comment by someCatInTheWorld** [comment]
So, are you going to merge this?

**Comment by nmsderp** [comment]
> So, are you going to merge this?

ill close it for now, but if the offline app dosen't turn out well i will merge it

**Pull request closed without merging**
